import { json, errorResponse } from '../lib/response.js';
import { normalizeMobile, isNonEmptyString } from '../lib/validate.js';
import { verifyPaymentSignature } from '../lib/razorpay.js';
import { getDocument, createDocument, patchDocument, queryDocuments } from '../lib/firestore.js';
import { grantPurchaseForVerifiedOrder } from '../lib/grantPurchase.js';

/**
 * POST /api/verify-payment
 * Body: { razorpay_order_id, razorpay_payment_id, razorpay_signature, mobile }
 *
 * This is the primary place (the webhook in webhook.js is the fallback)
 * that grants category access. The signature is ALWAYS recomputed
 * server-side with RAZORPAY_KEY_SECRET — values supplied by the browser
 * are never trusted on their own, no matter what Razorpay Checkout
 * reported client-side as "success". The categoryId being unlocked comes
 * from the server-recorded paymentOrders/{orderId} document (set at
 * /api/create-order time), never from the client, so it can't be tampered with.
 */
export async function handleVerifyPayment(request, env) {
  let body;
  try {
    body = await request.json();
  } catch {
    return errorResponse(env, 400, 'INVALID_JSON', 'Request body must be valid JSON.');
  }

  const orderId = body.razorpay_order_id;
  const paymentId = body.razorpay_payment_id;
  const signature = body.razorpay_signature;
  const mobile = normalizeMobile(body.mobile);

  if (!isNonEmptyString(orderId) || !isNonEmptyString(paymentId) || !isNonEmptyString(signature)) {
    return errorResponse(env, 400, 'MISSING_FIELDS', 'razorpay_order_id, razorpay_payment_id and razorpay_signature are required.');
  }
  if (!mobile) {
    return errorResponse(env, 400, 'INVALID_MOBILE', 'A valid 10-digit mobile number is required.');
  }

  // 1. Cryptographic verification — never trust the client's claim of success.
  let signatureValid;
  try {
    signatureValid = await verifyPaymentSignature(env, { orderId, paymentId, signature });
  } catch (err) {
    console.error('Signature verification error:', err.message);
    return errorResponse(env, 500, 'SIGNATURE_CHECK_FAILED', 'Unable to verify payment signature.');
  }

  if (!signatureValid) {
    try {
      await patchDocument(env, 'paymentOrders', orderId, { status: 'failed' });
    } catch (err) {
      console.error('Failed to mark order as failed:', err.message);
    }
    return errorResponse(env, 400, 'SIGNATURE_INVALID', 'Payment signature verification failed.');
  }

  // 2. Grant category access (idempotent, cross-checks mobile ownership of the order).
  let result;
  try {
    result = await grantPurchaseForVerifiedOrder(env, { orderId, paymentId, expectedMobile: mobile });
  } catch (err) {
    console.error('grantPurchaseForVerifiedOrder failed:', err.message);
    return errorResponse(env, 500, 'ACCESS_GRANT_FAILED', 'Payment verified but unlocking category access failed. Please contact support or retry.');
  }

  if (result.status === 'not_found') {
    return errorResponse(env, 404, 'ORDER_NOT_FOUND', 'Payment order not found.');
  }
  if (result.status === 'mobile_mismatch') {
    return errorResponse(env, 403, 'MOBILE_MISMATCH', 'This payment order does not belong to the given mobile number.');
  }

  // 3. Coupon post-verification flow — only for freshly verified orders.
  // If already_verified the couponUsage record was written on the first verification; skip entirely.
  if (result.status !== 'already_verified') {
    // 3a. Load the paymentOrders document FIRST to retrieve coupon fields before any writes.
    let orderDoc;
    try {
      orderDoc = await getDocument(env, 'paymentOrders', orderId);
    } catch (err) {
      console.error('Failed to load paymentOrders doc for coupon processing:', err.message);
      orderDoc = null;
    }

    const couponCode = orderDoc && orderDoc.couponCode ? orderDoc.couponCode : null;
    const categoryId = (orderDoc && orderDoc.categoryId) || result.categoryId || null;

    if (couponCode) {
      // 3b. Confirm coupon still exists in couponCodes by querying on the code field.
      // couponCodes use autogenerated Firestore document IDs; lookup must use code == couponCode.
      // If the coupon was deleted after payment, continue successfully — validity was already
      // checked at createOrder time.
      let couponStillExists = true;
      try {
        const couponDocs = await queryDocuments(env, 'couponCodes', [
          { field: 'code', op: '==', value: couponCode }
        ]);
        if (!couponDocs || couponDocs.length === 0) {
          console.warn(`Coupon Missing: coupon "${couponCode}" no longer exists in couponCodes. Continuing payment flow.`);
          couponStillExists = false;
        }
      } catch (err) {
        console.error(`Failed to look up couponCodes for "${couponCode}":`, err.message);
        // Treat as missing — do not block payment.
        couponStillExists = false;
      }

      // 3c. Atomically create the couponUsage document using Firestore's create semantics.
      // createDocument fails if the document already exists, making this race-condition safe
      // without a separate read-then-write check.
      // Doc ID includes categoryId so the same coupon can be reused for different campaigns.
      const couponUsageDocId = `${mobile}_${couponCode}_${categoryId}`;
      try {
        await createDocument(env, 'couponUsage', couponUsageDocId, {
          mobile,
          couponCode,
          categoryId,
          paymentOrderId: orderId,
          razorpayPaymentId: paymentId,
          usedAt: new Date()
        });
        console.log(`Coupon Usage Saved: mobile="${mobile}" couponCode="${couponCode}" orderId="${orderId}"`);
        if (couponStillExists) {
          console.log(`Coupon Used: mobile="${mobile}" couponCode="${couponCode}"`);
        }
      } catch (err) {
        // createDocument throws when the document already exists — this is the expected
        // duplicate-prevention path, not an error condition.
        if (err.code === 'ALREADY_EXISTS' || (err.message && err.message.includes('ALREADY_EXISTS'))) {
          console.log(`Coupon Already Used: mobile="${mobile}" couponCode="${couponCode}" — couponUsage record already exists, skipping duplicate.`);
        } else {
          // Genuine write failure — do NOT mark paymentOrders as verified yet.
          // Both writes must succeed together or both must fail.
          console.error(`Failed to write couponUsage for "${couponCode}":`, err.message);
          return errorResponse(env, 502, 'COUPON_USAGE_WRITE_FAILED', 'Payment verified but failed to record coupon usage. Please contact support.');
        }
      }
    }

    // 3d. Mark paymentOrders as verified AFTER couponUsage write succeeds.
    // This ensures both records are consistent: if couponUsage failed above we already returned.
    try {
      await patchDocument(env, 'paymentOrders', orderId, {
        verified: true,
        verifiedAt: new Date(),
        status: 'verified'
      });
    } catch (err) {
      console.error('Failed to mark paymentOrder as verified:', err.message);
      return errorResponse(env, 502, 'ORDER_UPDATE_FAILED', 'Payment verified but failed to update order record. Please contact support.');
    }
  }

  return json(env, {
    success: true,
    alreadyVerified: result.status === 'already_verified',
    categoryId: result.categoryId,
    paid: result.paid
  });
}
